### ISSUE TITLE
Radar plugin crashes at shutdown on Windows 10 Creators edition

### ISSUE THREAD

**Issue by douwefokkema** [canboat/BR24radar_pi#248]
Crash occurs most of the time but not always. Crash on m_receive->Wait(); after  m_receive->Shutdown(); for radar B only.

**Comment by canboat** [comment]
I changed the order in which various things happen in https://github.com/canboat/BR24radar_pi/commit/5925586c78b59f8bea277d0cf9c21da57f4186d6 which should fix this. The two Shutdown() calls are now done early, and then we wait for both threads to finish.

**Comment by douwefokkema** [comment]
Still crashing on shutdown. Unless wait is removed, then fine.
if (m_receive) {
     wxLongLong threadStartWait = wxGetUTCTimeMillis();
-    m_receive->Wait();
+  //  m_receive->Wait();
     wxLongLong threadEndWait = wxGetUTCTimeMillis();
     wxLongLong threadExtraWait = 0;

**Comment by canboat** [comment]
I will check in code that shuffles the shutdown code to stop the threads earlier, before we even close dialogs. This will come as an overall cleanup commit instigated by _valgrind_ and its _helgrind_ race condition detection module.

**Comment by canboat** [comment]
Please try again with https://github.com/canboat/BR24radar_pi/commit/be5d0a05269805729c7ef25ff969ebdc73f5e47d

If this doesn't help then we may have to add a config file option to not do the Wait(). I do not feel comfortable leaving it out -- it does actually clean up stuff as well as waiting.

**Comment by douwefokkema** [comment]
Perfect shutdown after be5d0a0 !
